name: QGexAR_test
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.4
  - python=3.9.7
  - flask=3.1.0
  - pip:
      - numpy==1.23.5
      - scikit-learn==1.1.3
      - scipy==1.13.1
      - tpot==0.11.7
      - tqdm==4.67.1
      - xgboost==1.5.0
